# Generated by Django 5.1.7 on 2025-03-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("pressure", models.FloatField()),
                ("humidity", models.FloatField()),
                ("equipment_temp", models.FloatField()),
                ("working_zone_temp", models.FloatField()),
                ("co2_level", models.FloatField()),
            ],
            options={
                "db_table": "process_data",
            },
        ),
    ]
