# Generated by Django 5.2 on 2025-06-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processdata',
            old_name='co2_level',
            new_name='electricity',
        ),
        migrations.RenameField(
            model_name='processdata',
            old_name='equipment_temp',
            new_name='gas',
        ),
        migrations.RenameField(
            model_name='processdata',
            old_name='humidity',
            new_name='heat',
        ),
        migrations.RenameField(
            model_name='processdata',
            old_name='pressure',
            new_name='water',
        ),
        migrations.RemoveField(
            model_name='processdata',
            name='working_zone_temp',
        ),
    ]
